# Task Analysis {.appendix}

Here are some questions to guide you through the process of doing a task analysis. You don't have to specifically answer each one of these (and some may not apply), but they should get you started thinking in the right direction.

What are the prerequisites, for both knowledge and e.g. software setup?

Someone completing the task would definitely have to have some background with plotting in R or any other software they decide to use. They would need to know and have a good understanding of biomarkers, and likely would have to have some base understanding of the equations and what they mean. Being able to interpret is pretty important as well.

What are the basic requirements for any data that the method is used on? - Are missing values allowed? - Should the data be confined within a certain range? - Does the data have to be approximately normally distributed?

From what I read, missing values would probably not want to be taken into account, but we would have to be careful with misrepresentation when cleaning out the data. This could be longer and tedious, but would be good for making sure that everything is taken into account. Generally ROC curves would need at least some normality, though it's not inherently needed.

What are the basic components of the task? - Outline these in a bit more detail

What decisions does the user need to be prepared to make on the fly?

-   What kind of data cleaning needs to be performed and how

-   Can things be assumed, or does further data need to be included?

What questions should the user ask of the "first draft" of the product? What adjustments may need to be made?

-   Is the description of the ROC curve and why it's used accurate? Are the interpretations correct?

-   Is the data correctly cleaned to avoid any bias that may come with messy data?

-   Is any personal bias removed from what is being written?

-   How can I make this clearer to someone who may not be as familiar with any of this material?

## Additional Guidance

Your check-in should answer these basic questions (and similar concerns that apply more directly to your topic).

Once you've completed the check-in, you can use this section to jump-start an introduction/set-up/getting started section in your user guide. This document should remain as an appendix to your main report.
